**import library numpy**

In [1]:
import numpy as np

**Membuat Data**

In [2]:
# generate 30 data bilangan real
data = np.random.randn(30)
data

array([-0.51651311,  0.76912404, -0.39929102, -0.31887593, -0.28429256,
       -0.4069794 , -1.13725227, -0.9354492 ,  1.179201  ,  0.27973718,
       -0.06776712,  1.26117046,  0.42460798, -0.7918722 , -2.55477942,
        0.59569251,  0.91669   ,  1.44134073, -1.11993313,  0.31701699,
        0.20724483, -0.91935745,  2.08500607, -0.54323315, -0.87337576,
       -1.97492794, -0.3853862 , -0.25312433, -0.00490494, -1.12812391])

In [3]:
# mengurutkan data
data = np.sort(data)
data

array([-2.55477942, -1.97492794, -1.13725227, -1.12812391, -1.11993313,
       -0.9354492 , -0.91935745, -0.87337576, -0.7918722 , -0.54323315,
       -0.51651311, -0.4069794 , -0.39929102, -0.3853862 , -0.31887593,
       -0.28429256, -0.25312433, -0.06776712, -0.00490494,  0.20724483,
        0.27973718,  0.31701699,  0.42460798,  0.59569251,  0.76912404,
        0.91669   ,  1.179201  ,  1.26117046,  1.44134073,  2.08500607])

In [4]:
# menghitung range
np.max(data) - np.min(data)

4.639785487958829

**Quartile**
Quartile membagi urutan-urutan data menjadi 4 bagian yang sama

In [5]:
# Quartile Pertama
Q1 = np.percentile(data,25)
Q1

-0.8529998695325994

In [6]:
# Quartile Kedua
Q2 = np.percentile(data,50)
Q2

-0.30158424637267545

In [7]:
# Quartile Ketiga
Q3 = np.percentile(data,75)
Q3

0.3977102355034557

**Interquatile Range**
$$IQR = Q_3 - Q_1$$

In [8]:
IQR = Q3 - Q1
IQR

1.2507101050360552

**Variance:**
Menunjukkan sejauh mana data tersebar dari rata-rata<br>
Rumus Variance untuk populasi
$$\sigma^2 = \frac{\displaystyle\sum_{i=1}^{n}(x_i - \mu)^2} {n}$$

Rumus Variance untuk sampel
$$S^2 = \frac{\displaystyle\sum_{i=1}^{n}(x_i - \mu)^2} {n}$$

In [9]:
# generate 100 data bilangan real
populasi = np.random.randn(100)

# mengurutkan data
populasi = np.sort(populasi)

populasi

array([-2.73876362, -1.93041598, -1.66884535, -1.50239297, -1.29039587,
       -1.27308197, -1.25442453, -1.25071032, -1.18351825, -1.17822923,
       -1.12468636, -1.04770237, -1.02158028, -1.01367204, -1.01348295,
       -0.9594527 , -0.84425105, -0.82552   , -0.82424657, -0.81857622,
       -0.8014207 , -0.77671906, -0.76012298, -0.66634609, -0.64052896,
       -0.60414523, -0.54965528, -0.51791153, -0.51406211, -0.44401545,
       -0.40324859, -0.38397889, -0.37909826, -0.33691014, -0.29193931,
       -0.26307118, -0.23119032, -0.22973208, -0.19456075, -0.15981007,
       -0.14892439, -0.14432962, -0.13337201, -0.05380987, -0.04212065,
       -0.03801804, -0.03611993, -0.02808271, -0.00685029,  0.015557  ,
        0.04868444,  0.05393255,  0.09082206,  0.17140204,  0.21799922,
        0.21947479,  0.21965805,  0.24928312,  0.32092243,  0.38606161,
        0.44102596,  0.46141971,  0.47440748,  0.48014835,  0.49584276,
        0.53024925,  0.53035731,  0.53351933,  0.56490397,  0.56

In [10]:
# generate 100 data bilangan real
sampel = np.random.choice(populasi, 20)

# mengurutkan data
sampel = np.sort(sampel)

sampel

array([-1.17822923, -1.01367204, -0.40324859, -0.33691014, -0.22973208,
        0.21947479,  0.24928312,  0.24928312,  0.38606161,  0.53024925,
        0.56490397,  0.65187136,  0.66585992,  0.76616398,  0.86407735,
        0.94386585,  1.05669867,  1.35121533,  1.50181959,  1.83102858])

**Menghitung Variance**

In [11]:
np.var(populasi)

0.8743504004804667

In [12]:
np.var(sampel)

0.57756373408323

**Standar Deviasi**
Standar Deviasi adalah akar dari variance<br>
Rumus standar deviasi untuk populasi

$$\sigma =\sqrt{\frac{\displaystyle\sum_{i=1}^{n}(x_i - \mu)^2} {n}}$$

Rumus standar deviasi untuk sampel
$$S =\sqrt{\frac{\displaystyle\sum_{i=1}^{n}(x_i - \mu)^2} {n}}$$


**Menghitung Standar Deviasi**


In [13]:
np.std(populasi)


0.9350670566758658

In [14]:
np.std(sampel)

0.7599761404697059