**import library numpy**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

**Membuat data**

In [2]:
# angka dari 7 - 10 sebanyak 20 buah
data = np.random.randint(7,10,20)
data

array([8, 7, 8, 8, 9, 9, 8, 8, 7, 9, 8, 9, 7, 8, 9, 8, 8, 7, 9, 7])

**Mean** adalah nilai rata-rata dari sebuah data.
$$\bar{X} = \frac{\sum_{}{}X_i} n$$

dimana X = data observasi; n = jumlah observasi


In [3]:
# mean atau rata-rata
np.mean(data)

8.05

**Median** adalah nilai tengah dari data ketika data tersebut telah diurutkan.

In [4]:
data = np.sort(data)
print(data)
np.median(data)

[7 7 7 7 7 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9]


8.0

**Mode** adalah nilai yang paling sering muncul dalam suatu data.

In [5]:
# Nilai modus dicari dengan fungsi mode
from statistics import mode
mode = mode(data)
mode

8

**Populasi dan Sampel**<br>
Populasi merupakan keseluruhan dari data yang ada.<br>
Sampel merupakan sebagian dari populasi.

In [6]:
# populasi data angka dari 1 sampai 9 sebanyak 100 buah
populasi = np.random.randint(1,10,100)
populasi

array([3, 7, 2, 4, 6, 3, 3, 8, 2, 7, 4, 2, 3, 8, 2, 1, 9, 1, 4, 7, 5, 6,
       8, 1, 2, 8, 6, 4, 3, 6, 5, 4, 4, 2, 2, 4, 7, 8, 1, 9, 4, 6, 4, 5,
       5, 6, 7, 1, 5, 6, 5, 7, 1, 5, 5, 9, 8, 6, 4, 2, 1, 2, 4, 3, 8, 5,
       1, 6, 1, 8, 2, 8, 5, 8, 5, 7, 3, 7, 7, 2, 8, 5, 6, 3, 9, 7, 8, 4,
       7, 1, 7, 4, 2, 4, 8, 9, 3, 3, 2, 6])

In [7]:
from statistics import mode
print("Mean :",np.mean(populasi))
print("Median :",np.median(populasi))
print("Mode :",mode(populasi))

Mean : 4.81
Median : 5.0
Mode : 4


**Mengambil sampel dari populasi**

In [8]:
sampel = np.random.choice(populasi, 20)
sampel

array([2, 6, 2, 5, 4, 8, 1, 6, 6, 6, 4, 6, 7, 4, 8, 5, 1, 3, 6, 8])

In [9]:
print("Mean :",np.mean(sampel))
print("Median :",np.median(sampel))
print("Modus :",mode(sampel))

Mean : 4.9
Median : 5.5
Modus : 6


**Mengambil sampel beberapa kali dari populasi**

In [10]:
sampel_1 = np.random.choice(populasi, 15)
sampel_2 = np.random.choice(populasi, 15)
sampel_3 = np.random.choice(populasi, 15)
sampel_4 = np.random.choice(populasi, 15)

In [11]:
# memuat sampel-sampel ke dalam list
data_sampel = [sampel_1, sampel_2, sampel_3, sampel_4]
mean_sampel = []

for x in data_sampel:
  mean_sampel.append(np.mean(x))

mean_sampel

[4.4, 5.333333333333333, 4.933333333333334, 5.266666666666667]

In [12]:
print("Mean dari sample", np.mean(mean_sampel))

Mean dari sample 4.983333333333333


In [13]:
print("Mean dari populasi", np.mean(populasi))

Mean dari populasi 4.81


**Terlihat mean populasi tidak jauh berbeda dari mean sampel**