**import library numpy**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

**Membuat data**

In [2]:
# angka dari 7 - 10 sebanyak 20 buah
data = np.random.randint(7,10,20)
data

array([8, 8, 9, 8, 7, 8, 9, 9, 8, 8, 9, 8, 9, 8, 7, 7, 9, 9, 8, 9])

**Mean** adalah nilai rata-rata dari sebuah data.
$$\bar{X} = \frac{\sum_{}{}X_i} n$$

dimana X = data observasi; n = jumlah observasi


In [3]:
# mean atau rata-rata
np.mean(data)

8.25

**Median** adalah nilai tengah dari data ketika data tersebut telah diurutkan.

In [4]:
data = np.sort(data)
print(data)
np.median(data)

[7 7 7 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9]


8.0

**Mode** adalah nilai yang paling sering muncul dalam suatu data.

In [5]:
# Nilai mode dicari dengan fungsi mode
import statistics
mode = statistics.mode(data)
mode

8

**Populasi dan Sampel**<br>
Populasi merupakan keseluruhan dari data yang ada.<br>
Sampel merupakan sebagian dari populasi.

In [6]:
# populasi data angka dari 1 sampai 9 sebanyak 100 buah
populasi = np.random.randint(1,10,100)
populasi

array([9, 7, 7, 7, 4, 5, 7, 8, 4, 2, 2, 7, 1, 5, 7, 4, 1, 5, 5, 7, 4, 5,
       5, 7, 7, 1, 5, 7, 7, 6, 8, 1, 9, 2, 6, 3, 2, 2, 1, 3, 7, 2, 2, 1,
       4, 5, 7, 8, 8, 9, 2, 5, 2, 9, 2, 4, 9, 4, 5, 6, 9, 9, 3, 5, 9, 5,
       8, 4, 9, 2, 5, 7, 2, 9, 3, 4, 9, 6, 4, 3, 1, 1, 2, 3, 2, 4, 9, 5,
       3, 8, 7, 5, 8, 5, 8, 8, 8, 8, 5, 1])

In [7]:

print("Mean :",np.mean(populasi))
print("Median :",np.median(populasi))
print("Mode :",statistics.mode(populasi))

Mean : 5.12
Median : 5.0
Mode : 5


**Mengambil sampel dari populasi**

In [8]:
sampel = np.random.choice(populasi, 20)
sampel

array([2, 7, 6, 4, 5, 5, 4, 1, 8, 5, 8, 2, 6, 8, 3, 9, 9, 3, 5, 9])

In [9]:
print("Mean :",np.mean(sampel))
print("Median :",np.median(sampel))
print("Mode :",statistics.mode(sampel))

Mean : 5.45
Median : 5.0
Mode : 5


**Mengambil sampel beberapa kali dari populasi**

In [10]:
sampel_1 = np.random.choice(populasi, 15)
sampel_2 = np.random.choice(populasi, 15)
sampel_3 = np.random.choice(populasi, 15)
sampel_4 = np.random.choice(populasi, 15)

In [11]:
# memuat sampel-sampel ke dalam list
data_sampel = [sampel_1, sampel_2, sampel_3, sampel_4]
mean_sampel = []

for x in data_sampel:
  mean_sampel.append(np.mean(x))

mean_sampel

[4.866666666666666, 5.266666666666667, 4.866666666666666, 5.133333333333334]

In [12]:
print("Mean dari sample", np.mean(mean_sampel))

Mean dari sample 5.033333333333333


In [13]:
print("Mean dari populasi", np.mean(populasi))

Mean dari populasi 5.12


**Terlihat mean populasi tidak jauh berbeda dari mean sampel**