**import library numpy**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

**Membuat data**

In [2]:
# angka dari 7 - 10 sebanyak 20 buah
data = np.random.randint(7,10,20)
data

array([9, 8, 7, 7, 9, 9, 8, 7, 9, 9, 8, 9, 9, 9, 8, 7, 7, 9, 8, 8])

**Mean** adalah nilai rata-rata dari sebuah data.
$$\bar{X} = \frac{\sum_{}{}X_i} n$$

dimana X = data observasi; n = jumlah observasi


In [3]:
# mean atau rata-rata
np.mean(data)

8.2

**Median** adalah nilai tengah dari data ketika data tersebut telah diurutkan.

In [4]:
data = np.sort(data)
print(data)
np.median(data)

[7 7 7 7 7 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9]


8.0

**Modus** adalah nilai yang paling sering muncul dalam suatu data.

In [5]:
# Nilai modus dicari dengan fungsi mode
from statistics import mode
modus = mode(data)
print (modus)

9


**Populasi dan Sampel**<br>
Populasi merupakan keseluruhan dari data yang ada.<br>
Sampel merupakan sebagian dari populasi.

In [6]:
# populasi data angka dari 1 sampai 9 sebanyak 100 buah
populasi = np.random.randint(1,10,100)
populasi

array([6, 1, 2, 9, 4, 3, 6, 8, 7, 8, 9, 7, 8, 7, 6, 9, 4, 5, 2, 7, 3, 3,
       2, 9, 3, 1, 8, 7, 4, 6, 2, 5, 1, 1, 7, 8, 3, 8, 7, 4, 8, 1, 8, 9,
       9, 7, 9, 6, 3, 2, 7, 1, 7, 5, 8, 4, 3, 5, 8, 5, 2, 8, 4, 1, 1, 5,
       1, 6, 2, 1, 2, 8, 2, 7, 2, 7, 3, 6, 4, 5, 7, 5, 7, 1, 7, 7, 5, 3,
       4, 5, 6, 9, 6, 3, 8, 2, 1, 8, 7, 8])

In [7]:
print("Mean :",np.mean(populasi))
print("Median :",np.median(populasi))
print("Modus :",mode(populasi))

Mean : 5.11
Median : 5.0
Modus : 7


**Mengambil sampel dari populasi**

In [8]:
sampel = np.random.choice(populasi, 20)
sampel

array([6, 2, 1, 2, 9, 6, 8, 5, 8, 5, 1, 1, 7, 3, 3, 8, 4, 4, 6, 1])

In [9]:
print("Mean :",np.mean(sampel))
print("Median :",np.median(sampel))
print("Modus :",mode(sampel))

Mean : 4.5
Median : 4.5
Modus : 1


**Mengambil sampel beberapa kali dari populasi**

In [10]:
sampel_1 = np.random.choice(populasi, 15)
sampel_2 = np.random.choice(populasi, 15)
sampel_3 = np.random.choice(populasi, 15)
sampel_4 = np.random.choice(populasi, 15)

In [11]:
# memuat sampel-sampel ke dalam list
data_sampel = [sampel_1, sampel_2, sampel_3, sampel_4]
mean_sampel = []

for x in data_sampel:
  mean_sampel.append(np.mean(x))

mean_sampel

[4.866666666666666, 5.2, 4.8, 4.8]

In [12]:
print("Mean dari sample", np.mean(mean_sampel))

Mean dari sample 4.916666666666667


In [13]:
print("Mean dari populasi", np.mean(populasi))

Mean dari populasi 5.11


**Terlihat mean populasi tidak jauh berbeda dari mean sampel**